# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobilephone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
