# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('send_type', models.CharField(choices=[('register', 'email'), ('forget', 'modifypassword'), ('update_email', 'modify_email')], max_length=18)),
                ('send_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'emailcode',
            },
        ),
    ]
