# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_auto_20171009_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'man'), ('female', 'woman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
