# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0009_auto_20171012_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
