# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="teacher's name")),
                ('work_years', models.IntegerField(default=0)),
                ('work_company', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('poits', models.CharField(max_length=50, verbose_name='hao teach')),
                ('click_nums', models.IntegerField(default=0)),
                ('fav_nums', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('pxjg', 'pxjg'), ('gr', 'gr'), ('gx', 'gx')], default='pxjg', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='click_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='fav_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(default='', upload_to='organization/%Y/%m'),
        ),
        migrations.AddField(
            model_name='organization',
            name='students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='tag',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganizationInfo.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganizationInfo.CityDict'),
        ),
    ]
