# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrganizationInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('learn_time', models.IntegerField()),
                ('image', models.ImageField(upload_to='course_image/%Y/%m')),
                ('learn_num', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrganizationInfo.Organization')),
            ],
        ),
    ]
