# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0002_auto_20171013_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fav_num',
            field=models.IntegerField(default=0),
        ),
    ]
