# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0003_course_fav_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='click_num',
            field=models.IntegerField(default=0),
        ),
    ]
