# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizationInfo', '0002_auto_20171014_1700'),
        ('CourseInfo', '0005_auto_20171014_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganizationInfo.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganizationInfo.Organization'),
        ),
    ]
