# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0008_auto_20171016_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_style',
            field=models.ManyToManyField(blank=True, to='CourseInfo.Course_style', verbose_name='课程类型'),
        ),
    ]
