# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseInfo', '0009_auto_20171016_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='course_category',
            options={'verbose_name': '课程分类', 'verbose_name_plural': '课程分类'},
        ),
        migrations.AlterModelOptions(
            name='course_style',
            options={'verbose_name': '课程类型', 'verbose_name_plural': '课程类型'},
        ),
        migrations.AlterModelOptions(
            name='course_tag',
            options={'verbose_name': '课程方向', 'verbose_name_plural': '课程方向'},
        ),
    ]
