# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20171016_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='Test.Author'),
        ),
    ]
